/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bb64fced-12e4-4e0f-841e-daafa3325e90",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_410H7fZl7",
    "aws_user_pools_web_client_id": "oe19p62g74idr8ts10epl7sn1",
    "oauth": {}
};


export default awsmobile;
